### ISSUE TITLE
support cuDNN V5?

### ISSUE THREAD

**Issue by ruizhaogit** [chuckcho/video-caffe#18]
Hi @chuckcho 

I compiled this video-caffe with cuDNN v5.0.5 for CUDA 8.0, but got errors like following.

So, does this version of Caffe not support cuDNN v5?

Best,
Rui

```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   v1.0-rc0-3653-g0089f35-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.0)
--   lmdb              :   Yes (ver. 0.9.14)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 5.0.5)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.9)
--   Libraries         :   /usr/lib64/libpython2.7.so (ver 2.7.9)
--   NumPy             :   /usr/lib64/python2.7/site-packages/numpy/core/include (ver 1.10.4)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.6)
--   config_file       :   /home_local/C3D/new/video-caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home_local/C3D/new/video-caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home_local/C3D/new/video-caffe/build
```

`host:/home_local/C3D/new/video-caffe/build> make clean`
`hosr:/home_local/C3D/new/video-caffe/build> make all`

```
[  1%] Running C++/Python protocol buffer compiler on /home_local/C3D/new/video-caffe/src/caffe/proto/caffe.proto
Scanning dependencies of target proto
[  1%] Building CXX object src/caffe/CMakeFiles/proto.dir/__/__/include/caffe/proto/caffe.pb.cc.o
[  1%] Linking CXX static library ../../lib/libproto.a
[  1%] Built target proto
[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o
/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(152): error: argument of type "int *" is incompatible with parameter of type "cudnnTensorFormat_t *"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(153): error: too few arguments in function call

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(186): error: argument of type "int" is incompatible with parameter of type "cudnnNanPropagation_t"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(186): error: too few arguments in function call

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: argument of type "std::size_t" is incompatible with parameter of type "cudnnNanPropagation_t"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: argument of type "int *" is incompatible with parameter of type "int"

/home_local/C3D/new/video-caffe/include/caffe/util/cudnn.hpp(209): error: too few arguments in function call

7 errors detected in the compilation of "/tmp/tmpxft_00007f09_00000000-5_eltwise_layer.cpp4.ii".
CMake Error at cuda_compile_generated_eltwise_layer.cu.o.cmake:266 (message):
  Error generating file
  /home_local/C3D/new/video-caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_eltwise_layer.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:469: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_eltwise_layer.cu.o] Error 1
CMakeFiles/Makefile2:235: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by chuckcho** [comment]
@ruizhaogit not yet. I'll work on it in a week or two. It should be straight-forward to make changes. I welcome public contributions on this issue. :)

**Comment by ruizhaogit** [comment]
@chuckcho Good to know. But the video-caffe should also work with CUDA 8.0 and cuDNN v4, right?

**Comment by chuckcho** [comment]
@ruizhaogit cudnn v4 is known to work, but I haven't tested CUDA8.0 (RC now?)

**Comment by ruizhaogit** [comment]
@chuckcho Yeah, the CUDA8.0 (RC) version. It is sucessfully built, but runs into some errors in runtests, such as [  FAILED  ] CuDNNConvolutionLayerTest/0.TestGradientGroupCuDNN, where TypeParam = float (2656 ms).

**Comment by ruizhaogit** [comment]
@chuckcho What do you mean "straight-forward to make changes"? like merge the standard caffe with video-caffe? Can you tell me, how to do that?
And when will this version be support to cuDNN V5? like in two weeks?
I really want to test this video-caffe on the new GPU.

**Comment by chuckcho** [comment]
@ruizhaogit unfortunately i don't have any resource to work on this project right now. if it builds fine, but crashes in run-time, it may be tricky to fix. is `TestGradientGroupCuDNN` only test that fails? i would first check what tests it fails.

**Comment by ruizhaogit** [comment]
@chuckcho hey, yeah, it is the only test failed. And then the 3d cnn model was not converging anymore. In the worst case, when will the video caffe support cudnn v5 + cuda 8 or cudnn v5 + cuda 8 ?

**Comment by chuckcho** [comment]
i'll at least wait for CUDA8.0 to be an official release. isn't it an option to have cuda7.5 + cudnn4 installed temporarily (doesn't have to be in `/usr/local/`), and build with / link to that.

**Comment by ruizhaogit** [comment]
@chuckcho Yeah, I tried that before. It gave more runtests errors, might because the pascal architecture of the gpu. Cuda 7.5 doesn't support compute capability 6.0 well. So,  I think I have to use cuda 8.0 and cudnn 5, because of the gtx 1080 gpu. Hope can use your video caffe soon :)

**Comment by chuckcho** [comment]
wow. you're using the latest and greatest GPU! :+1:

**Comment by ruizhaogit** [comment]
@chuckcho by the way, I built the newest standard caffe with cuda v5 and cuda 8. It passed all the runtests and works fun. The problem is that I don't know how to use the standard caffe to classify video. Do you know how to do that?

**Comment by chuckcho** [comment]
don't think there's a quick and easy way to do it unless you first convert your videos into HDF5 or caffe-compatible format, which i haven't tried.

**Comment by futurely** [comment]
Some compilation errors with cudnn v5 are as follows.
```
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::setNdConvolutionDesc(cudnnConvolutionStruct**, cudnnTensorDescriptor_t, cudnnFilterDescriptor_t, std::vector<int>, std::vector<int>)’:
./include/caffe/util/cudnn.hpp:158:19: error: cannot convert ‘int*’ to ‘cudnnTensorFormat_t*’ for argument ‘4’ to ‘cudnnStatus_t cudnnGetFilterNdDescriptor(cudnnFilterDescriptor_t, int, cudnnDataType_t*, cudnnTensorFormat_t*, int*, int*)’
       shape.data());
                   ^
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::createNdPoolingDesc(cunnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, std::vector<int>, std::vector<int>, std::vector<int>)’:
./include/caffe/util/cudnn.hpp:220:54: error: too few arguments to function ‘cudnnStatus_t cudnnSetPoolingNdDescriptor(cudnnPoolingDescriptor_t, cudnnPoolingMode_t, cudnnNanPropagation_t, int, const int*, const int*, const int*)’
               shape.data(), pad.data(), stride.data()));
                                                      ^
```

**Comment by chuckcho** [comment]
This is closed, as video-caffe now supports cuDNN v5 / v4. kudos to @futurely!
